#!/usr/bin/env bash

export INPUT_FILE=/tmp/aIn
export OUTPUT_FILE=/tmp/aOut

if [[ -e $INPUT_FILE ]]; then
  rm $INPUT_FILE
fi 
mkfifo $INPUT_FILE

if [[ -e $OUTPUT_FILE ]]; then
  rm $OUTPUT_FILE
fi
mkfifo $OUTPUT_FILE 

trap 'kill 0' EXIT
coproc forge script --ffi EchoAll

echo -n "> "
while IFS='$\n' read -r LINE; do
  echo "$LINE" >$INPUT_FILE
  read IN <$OUTPUT_FILE
  echo $IN
  echo -n "> "
done
