#!/usr/bin/env bash

export INPUT_FILE=/tmp/aIn
export OUTPUT_FILE=/tmp/aOut

if [[ -e $INPUT_FILE ]]; then
  rm $INPUT_FILE
fi 
mkfifo $INPUT_FILE

if [[ -e $OUTPUT_FILE ]]; then
  rm $OUTPUT_FILE
fi
mkfifo $OUTPUT_FILE 

exec 3>$OUTPUT_FILE
trap "exec 3>&-" SIGINT SIGTERM 
export OUTPUT_FILE="&3"
forge script --ffi EchoAll -vvv
